// Minimal subset of LVGL 9's font format. The font_*.c files we ship under
// this directory were generated by lv_font_conv against the original
// Anthropic OTFs and copied verbatim from github.com/HermannBjorgvin/Clawdmeter.
// To use them without pulling LVGL itself in we provide just enough of the
// LVGL type signatures here that the static const initializers in the .c
// files compile, and our draw_text.cpp walks the resulting data structure
// directly. The function-pointer slots in lv_font_t are never invoked.
//
// Field layouts intentionally use SMALL fixed-width types. The .c files
// initialize with values that comfortably fit; binary compatibility with
// real LVGL is irrelevant because the data is built in-process at link time.
#pragma once

// Pull in stddef for size_t etc., then force NULL = integer 0 so that the
// font files' `.field = NULL` initializers convert cleanly to any pointer
// type (including function pointers) as a constant null-pointer expression.
// stddef's `((void *)0)` flavor of NULL trips ISO C99's strict
// "initializer element is not constant" rule for function-pointer fields.
#include <stddef.h>
#ifdef NULL
#  undef NULL
#endif
#define NULL 0

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Constants the .c files reference at init time.
#define LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY 0
#define LV_FONT_FMT_TXT_CMAP_FORMAT0_FULL 1
#define LV_FONT_FMT_TXT_CMAP_SPARSE_TINY  2
#define LV_FONT_FMT_TXT_CMAP_SPARSE_FULL  3
#define LV_FONT_SUBPX_NONE 0
#define LV_ATTRIBUTE_LARGE_CONST

typedef struct {
    uint32_t bitmap_index;
    uint16_t adv_w;
    uint8_t  box_w;
    uint8_t  box_h;
    int8_t   ofs_x;
    int8_t   ofs_y;
} lv_font_fmt_txt_glyph_dsc_t;

typedef struct {
    uint32_t  range_start;
    uint16_t  range_length;
    uint16_t  glyph_id_start;
    const uint16_t * unicode_list;
    const void *     glyph_id_ofs_list;
    uint16_t  list_length;
    uint8_t   type;
} lv_font_fmt_txt_cmap_t;

typedef struct {
    const uint8_t * glyph_ids;
    const int8_t  * values;
    uint32_t pair_cnt;
    uint8_t  glyph_ids_size;
} lv_font_fmt_txt_kern_pair_t;

typedef struct {
    const uint8_t * glyph_bitmap;
    const lv_font_fmt_txt_glyph_dsc_t * glyph_dsc;
    const lv_font_fmt_txt_cmap_t * cmaps;
    const lv_font_fmt_txt_kern_pair_t * kern_dsc;
    uint16_t kern_scale;
    uint16_t cmap_num;
    uint8_t  bpp;
    uint8_t  kern_classes;
    uint8_t  bitmap_format;
} lv_font_fmt_txt_dsc_t;

// Function pointer slots are never invoked — use the simplest type that
// accepts the LVGL function symbols at init time and accepts NULL.
typedef void (*lv_font_cb_t)(void);

struct lv_font_struct;
typedef struct lv_font_struct {
    lv_font_cb_t get_glyph_dsc;
    lv_font_cb_t get_glyph_bitmap;
    lv_font_cb_t release_glyph;
    int32_t line_height;
    int32_t base_line;
    uint8_t subpx          : 2;
    uint8_t kerning        : 1;
    uint8_t static_bitmap  : 1;
    uint8_t _reserved      : 4;
    int8_t  underline_position;
    int8_t  underline_thickness;
    const void * dsc;
    const struct lv_font_struct * fallback;
    void * user_data;
} lv_font_t;

// Stubs — referenced by the font .c file initializers but never executed.
extern void lv_font_get_glyph_dsc_fmt_txt(void);
extern void lv_font_get_bitmap_fmt_txt(void);

#ifdef __cplusplus
}
#endif
